[2017-12-11 19:29:35.036] [ERROR] Error - { Error: Not Found
    at Exception (f:\KMSP\BACKEND\API\Branch\Code\framework\exception\exception.js:5:9)
    at NotFoundException (f:\KMSP\BACKEND\API\Branch\Code\framework\exception\notFoundException.js:12:9)
    at module.exports (f:\KMSP\BACKEND\API\Branch\Code\framework\httpServer\routes\router-not-found.js:12:10)
    at Layer.handle [as handle_request] (f:\KMSP\BACKEND\API\Branch\Code\node_modules\express\lib\router\layer.js:95:5)
    at trim_prefix (f:\KMSP\BACKEND\API\Branch\Code\node_modules\express\lib\router\index.js:312:13)
    at f:\KMSP\BACKEND\API\Branch\Code\node_modules\express\lib\router\index.js:280:7
    at Function.process_params (f:\KMSP\BACKEND\API\Branch\Code\node_modules\express\lib\router\index.js:330:12)
    at next (f:\KMSP\BACKEND\API\Branch\Code\node_modules\express\lib\router\index.js:271:10)
    at f:\KMSP\BACKEND\API\Branch\Code\node_modules\express\lib\router\index.js:618:15
    at next (f:\KMSP\BACKEND\API\Branch\Code\node_modules\express\lib\router\index.js:256:14)
    at Function.handle (f:\KMSP\BACKEND\API\Branch\Code\node_modules\express\lib\router\index.js:176:3)
    at router (f:\KMSP\BACKEND\API\Branch\Code\node_modules\express\lib\router\index.js:46:12)
    at Layer.handle [as handle_request] (f:\KMSP\BACKEND\API\Branch\Code\node_modules\express\lib\router\layer.js:95:5)
    at trim_prefix (f:\KMSP\BACKEND\API\Branch\Code\node_modules\express\lib\router\index.js:312:13)
    at f:\KMSP\BACKEND\API\Branch\Code\node_modules\express\lib\router\index.js:280:7
    at Function.process_params (f:\KMSP\BACKEND\API\Branch\Code\node_modules\express\lib\router\index.js:330:12) statusCode: 404, code: 404 }
[2017-12-11 19:29:39.812] [ERROR] Error - { Error: 访问未授权.
    at Exception (f:\KMSP\BACKEND\API\Branch\Code\framework\exception\exception.js:5:9)
    at AuthException (f:\KMSP\BACKEND\API\Branch\Code\framework\exception\authException.js:12:9)
    at __dirname.static.auth.AuthCtrl.getTokenObj (f:\KMSP\BACKEND\API\Branch\Code\api\controllers\authCtrl.js:35:29)
    at Function.getTokenObj (f:\KMSP\BACKEND\API\Branch\Code\api\controllers\authCtrl.js:74:20)
    at Function.auth (f:\KMSP\BACKEND\API\Branch\Code\api\controllers\authCtrl.js:33:18)
    at module.exports.pipe.funs (f:\KMSP\BACKEND\API\Branch\Code\framework\httpServer\routes\router.js:62:26)
    at Layer.handle [as handle_request] (f:\KMSP\BACKEND\API\Branch\Code\node_modules\express\lib\router\layer.js:95:5)
    at next (f:\KMSP\BACKEND\API\Branch\Code\node_modules\express\lib\router\route.js:131:13)
    at listener (f:\KMSP\BACKEND\API\Branch\Code\framework\httpServer\routes\router.js:146:9)
    at Layer.handle [as handle_request] (f:\KMSP\BACKEND\API\Branch\Code\node_modules\express\lib\router\layer.js:95:5)
    at next (f:\KMSP\BACKEND\API\Branch\Code\node_modules\express\lib\router\route.js:131:13)
    at Route.dispatch (f:\KMSP\BACKEND\API\Branch\Code\node_modules\express\lib\router\route.js:112:3)
    at Layer.handle [as handle_request] (f:\KMSP\BACKEND\API\Branch\Code\node_modules\express\lib\router\layer.js:95:5)
    at f:\KMSP\BACKEND\API\Branch\Code\node_modules\express\lib\router\index.js:277:22
    at Function.process_params (f:\KMSP\BACKEND\API\Branch\Code\node_modules\express\lib\router\index.js:330:12)
    at next (f:\KMSP\BACKEND\API\Branch\Code\node_modules\express\lib\router\index.js:271:10) statusCode: 401 }
[2017-12-11 20:57:42.938] [ERROR] Error - { Error: 访问未授权.
    at Exception (f:\KMSP\BACKEND\API\Branch\Code\framework\exception\exception.js:5:9)
    at AuthException (f:\KMSP\BACKEND\API\Branch\Code\framework\exception\authException.js:12:9)
    at __dirname.static.auth.AuthCtrl.getTokenObj (f:\KMSP\BACKEND\API\Branch\Code\api\controllers\auth-Ctrl.js:37:29)
    at Function.getTokenObj (f:\KMSP\BACKEND\API\Branch\Code\api\controllers\auth-Ctrl.js:76:20)
    at Function.auth (f:\KMSP\BACKEND\API\Branch\Code\api\controllers\auth-Ctrl.js:35:18)
    at module.exports.pipe.funs (f:\KMSP\BACKEND\API\Branch\Code\framework\httpServer\routes\router.js:62:26)
    at Layer.handle [as handle_request] (f:\KMSP\BACKEND\API\Branch\Code\node_modules\express\lib\router\layer.js:95:5)
    at next (f:\KMSP\BACKEND\API\Branch\Code\node_modules\express\lib\router\route.js:131:13)
    at listener (f:\KMSP\BACKEND\API\Branch\Code\framework\httpServer\routes\router.js:146:9)
    at Layer.handle [as handle_request] (f:\KMSP\BACKEND\API\Branch\Code\node_modules\express\lib\router\layer.js:95:5)
    at next (f:\KMSP\BACKEND\API\Branch\Code\node_modules\express\lib\router\route.js:131:13)
    at Route.dispatch (f:\KMSP\BACKEND\API\Branch\Code\node_modules\express\lib\router\route.js:112:3)
    at Layer.handle [as handle_request] (f:\KMSP\BACKEND\API\Branch\Code\node_modules\express\lib\router\layer.js:95:5)
    at f:\KMSP\BACKEND\API\Branch\Code\node_modules\express\lib\router\index.js:277:22
    at Function.process_params (f:\KMSP\BACKEND\API\Branch\Code\node_modules\express\lib\router\index.js:330:12)
    at next (f:\KMSP\BACKEND\API\Branch\Code\node_modules\express\lib\router\index.js:271:10) statusCode: 401 }
[2017-12-11 20:57:48.282] [ERROR] Error - { Error: 访问未授权.
    at Exception (f:\KMSP\BACKEND\API\Branch\Code\framework\exception\exception.js:5:9)
    at AuthException (f:\KMSP\BACKEND\API\Branch\Code\framework\exception\authException.js:12:9)
    at __dirname.static.auth.AuthCtrl.getTokenObj (f:\KMSP\BACKEND\API\Branch\Code\api\controllers\auth-Ctrl.js:37:29)
    at Function.getTokenObj (f:\KMSP\BACKEND\API\Branch\Code\api\controllers\auth-Ctrl.js:76:20)
    at Function.auth (f:\KMSP\BACKEND\API\Branch\Code\api\controllers\auth-Ctrl.js:35:18)
    at module.exports.pipe.funs (f:\KMSP\BACKEND\API\Branch\Code\framework\httpServer\routes\router.js:62:26)
    at Layer.handle [as handle_request] (f:\KMSP\BACKEND\API\Branch\Code\node_modules\express\lib\router\layer.js:95:5)
    at next (f:\KMSP\BACKEND\API\Branch\Code\node_modules\express\lib\router\route.js:131:13)
    at listener (f:\KMSP\BACKEND\API\Branch\Code\framework\httpServer\routes\router.js:146:9)
    at Layer.handle [as handle_request] (f:\KMSP\BACKEND\API\Branch\Code\node_modules\express\lib\router\layer.js:95:5)
    at next (f:\KMSP\BACKEND\API\Branch\Code\node_modules\express\lib\router\route.js:131:13)
    at Route.dispatch (f:\KMSP\BACKEND\API\Branch\Code\node_modules\express\lib\router\route.js:112:3)
    at Layer.handle [as handle_request] (f:\KMSP\BACKEND\API\Branch\Code\node_modules\express\lib\router\layer.js:95:5)
    at f:\KMSP\BACKEND\API\Branch\Code\node_modules\express\lib\router\index.js:277:22
    at Function.process_params (f:\KMSP\BACKEND\API\Branch\Code\node_modules\express\lib\router\index.js:330:12)
    at next (f:\KMSP\BACKEND\API\Branch\Code\node_modules\express\lib\router\index.js:271:10) statusCode: 401 }
[2017-12-11 21:00:57.716] [ERROR] Error - TypeError: next is not a function
    at Object.auth [as validater] (f:\KMSP\BACKEND\API\Branch\Code\api\validates\auth-validater.js:12:10)
    at module.exports.pipe.funs (f:\KMSP\BACKEND\API\Branch\Code\framework\httpServer\routes\router.js:67:33)
    at Layer.handle [as handle_request] (f:\KMSP\BACKEND\API\Branch\Code\node_modules\express\lib\router\layer.js:95:5)
    at next (f:\KMSP\BACKEND\API\Branch\Code\node_modules\express\lib\router\route.js:131:13)
    at Function.auth (f:\KMSP\BACKEND\API\Branch\Code\api\controllers\auth-Ctrl.js:29:20)
    at module.exports.pipe.funs (f:\KMSP\BACKEND\API\Branch\Code\framework\httpServer\routes\router.js:62:26)
    at Layer.handle [as handle_request] (f:\KMSP\BACKEND\API\Branch\Code\node_modules\express\lib\router\layer.js:95:5)
    at next (f:\KMSP\BACKEND\API\Branch\Code\node_modules\express\lib\router\route.js:131:13)
    at listener (f:\KMSP\BACKEND\API\Branch\Code\framework\httpServer\routes\router.js:146:9)
    at Layer.handle [as handle_request] (f:\KMSP\BACKEND\API\Branch\Code\node_modules\express\lib\router\layer.js:95:5)
    at next (f:\KMSP\BACKEND\API\Branch\Code\node_modules\express\lib\router\route.js:131:13)
    at Route.dispatch (f:\KMSP\BACKEND\API\Branch\Code\node_modules\express\lib\router\route.js:112:3)
    at Layer.handle [as handle_request] (f:\KMSP\BACKEND\API\Branch\Code\node_modules\express\lib\router\layer.js:95:5)
    at f:\KMSP\BACKEND\API\Branch\Code\node_modules\express\lib\router\index.js:277:22
    at Function.process_params (f:\KMSP\BACKEND\API\Branch\Code\node_modules\express\lib\router\index.js:330:12)
    at next (f:\KMSP\BACKEND\API\Branch\Code\node_modules\express\lib\router\index.js:271:10)
[2017-12-11 21:01:32.778] [ERROR] Error - TypeError: next is not a function
    at Object.auth [as validater] (f:\KMSP\BACKEND\API\Branch\Code\api\validates\auth-validater.js:12:10)
    at module.exports.pipe.funs (f:\KMSP\BACKEND\API\Branch\Code\framework\httpServer\routes\router.js:67:33)
    at Layer.handle [as handle_request] (f:\KMSP\BACKEND\API\Branch\Code\node_modules\express\lib\router\layer.js:95:5)
    at next (f:\KMSP\BACKEND\API\Branch\Code\node_modules\express\lib\router\route.js:131:13)
    at Function.auth (f:\KMSP\BACKEND\API\Branch\Code\api\controllers\auth-Ctrl.js:29:20)
    at module.exports.pipe.funs (f:\KMSP\BACKEND\API\Branch\Code\framework\httpServer\routes\router.js:62:26)
    at Layer.handle [as handle_request] (f:\KMSP\BACKEND\API\Branch\Code\node_modules\express\lib\router\layer.js:95:5)
    at next (f:\KMSP\BACKEND\API\Branch\Code\node_modules\express\lib\router\route.js:131:13)
    at listener (f:\KMSP\BACKEND\API\Branch\Code\framework\httpServer\routes\router.js:146:9)
    at Layer.handle [as handle_request] (f:\KMSP\BACKEND\API\Branch\Code\node_modules\express\lib\router\layer.js:95:5)
    at next (f:\KMSP\BACKEND\API\Branch\Code\node_modules\express\lib\router\route.js:131:13)
    at Route.dispatch (f:\KMSP\BACKEND\API\Branch\Code\node_modules\express\lib\router\route.js:112:3)
    at Layer.handle [as handle_request] (f:\KMSP\BACKEND\API\Branch\Code\node_modules\express\lib\router\layer.js:95:5)
    at f:\KMSP\BACKEND\API\Branch\Code\node_modules\express\lib\router\index.js:277:22
    at Function.process_params (f:\KMSP\BACKEND\API\Branch\Code\node_modules\express\lib\router\index.js:330:12)
    at next (f:\KMSP\BACKEND\API\Branch\Code\node_modules\express\lib\router\index.js:271:10)
[2017-12-11 21:02:17.849] [ERROR] Error - { Error: 验证url不能为空.
    at Exception (f:\KMSP\BACKEND\API\Branch\Code\framework\exception\exception.js:5:9)
    at BusinessException (f:\KMSP\BACKEND\API\Branch\Code\framework\exception\businessException.js:11:9)
    at Object.auth [as validater] (f:\KMSP\BACKEND\API\Branch\Code\api\validates\auth-validater.js:11:10)
    at module.exports.pipe.funs (f:\KMSP\BACKEND\API\Branch\Code\framework\httpServer\routes\router.js:67:33)
    at Layer.handle [as handle_request] (f:\KMSP\BACKEND\API\Branch\Code\node_modules\express\lib\router\layer.js:95:5)
    at next (f:\KMSP\BACKEND\API\Branch\Code\node_modules\express\lib\router\route.js:131:13)
    at Function.auth (f:\KMSP\BACKEND\API\Branch\Code\api\controllers\auth-Ctrl.js:29:20)
    at module.exports.pipe.funs (f:\KMSP\BACKEND\API\Branch\Code\framework\httpServer\routes\router.js:62:26)
    at Layer.handle [as handle_request] (f:\KMSP\BACKEND\API\Branch\Code\node_modules\express\lib\router\layer.js:95:5)
    at next (f:\KMSP\BACKEND\API\Branch\Code\node_modules\express\lib\router\route.js:131:13)
    at listener (f:\KMSP\BACKEND\API\Branch\Code\framework\httpServer\routes\router.js:146:9)
    at Layer.handle [as handle_request] (f:\KMSP\BACKEND\API\Branch\Code\node_modules\express\lib\router\layer.js:95:5)
    at next (f:\KMSP\BACKEND\API\Branch\Code\node_modules\express\lib\router\route.js:131:13)
    at Route.dispatch (f:\KMSP\BACKEND\API\Branch\Code\node_modules\express\lib\router\route.js:112:3)
    at Layer.handle [as handle_request] (f:\KMSP\BACKEND\API\Branch\Code\node_modules\express\lib\router\layer.js:95:5)
    at f:\KMSP\BACKEND\API\Branch\Code\node_modules\express\lib\router\index.js:277:22 statusCode: 400 }
